title: Ping-Hsuan Tsai
tagline: CFD, HPC, and Reduced-Order Modeling Researcher
#description: CFD | HPC | Reduced-Order Modeling
author:
  name: Ping-Hsuan Tsai
  url: https://ping-hsuan.github.io/
  email: pinghsuan@vt.edu
social:
  name: Ping-Hsuan Tsai
  links:
    - https://github.com/ping-hsuan
    - https://www.linkedin.com/in/ping-hsuan-tsai-8a19701b9/
keywords: HPC, reduced-order modeling, computational fluid dynamics, turbulent flows

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
- jekyll-sitemap

header_pages:
  - index.md
  - about.md
  - contact.md

# Enable syntax highlighting
highlighter: rouge

logo: /images/headshot.JPG

# Make sure you have this line to link your custom style.css
css:
  - "assets/css/style.scss"