title: Ping-Hsuan Tsai

#description: Welcome to my site!
description: Computational Fluid Dynamics | HPC | Reduced-Order Modeling
url: https://ping-hsuan.github.io/


remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag
- jekyll-sitemap

header_pages:
  - index.md
  - about.md
  - contact.md

# Enable syntax highlighting
highlighter: rouge

logo: /images/headshot.JPG

# Make sure you have this line to link your custom style.css
css:
  - "assets/css/style.scss"