title: Ping-Hsuan Tsai
description: Welcome to my site!
theme: minimal-mistakes-jekyll
header_pages:
  - index.md
  - about.md
  - contact.md

# Enable syntax highlighting
highlighter: rouge

# Make sure you have this line to link your custom style.css
css:
  - "assets/css/style.css"